[[plugins]] # プラグイン管理
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/vimshell'
rev  = '3787e5'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]] # ファイルオープン
repo = 'Shougo/unite.vim'

[[plugins]] # Unite.vimで最近使ったファイルを表示
repo = 'Shougo/neomru.vim'

[[plugins]] # ファイルタイプの判定
repo = 'Shougo/context_filetype.vim'

[[plugins]] # ファイルをtree表示
repo = 'scrooloose/nerdtree'

[[plugins]] # インデントに色を付ける
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]] # 行末の半角スペースを可視化
repo = 'bronson/vim-trailing-whitespace'

[[plugins]] # テキストオブジェクトの拡張
repo = 'tpope/vim-surround'

[[plugins]] # レジスタの履歴を取得・再利用する
repo = 'LeafCage/yankround.vim'

[[plugins]] # シンタックスチェック
repo = 'w0rp/ale'

[[plugins]] # コメントON/OFF
repo = 'tomtom/tcomment_vim'

[[plugins]] # カラースキーム
repo = 'jacoborus/tender'

[[plugins]] # 複数の検索結果のハイライト
repo = 't9md/vim-quickhl'

[[plugins]] # ビジュアルモードで選択した文字列を検索
repo = 'thinca/vim-visualstar'

[[plugins]] # 検索
repo = 'haya14busa/incsearch.vim'

[[plugins]] # プロジェクト固有の設定を読み込む
repo = 'thinca/vim-localrc'

[[plugins]] # 同じファイルの同時起動防止
repo = 'thinca/vim-singleton'

[[plugins]] # editorconfig
repo = 'sgur/vim-editorconfig'

[[plugins]] # git操作
repo = 'tpope/vim-fugitive'

[[plugins]] # gitの差分を表示する
repo = 'airblade/vim-gitgutter'

[[plugins]] # カーソル移動
repo = 'easymotion/vim-easymotion'

[[plugins]] # ステータスライン
repo = 'itchyny/lightline.vim'

[[plugins]] # 文章書くときにいい感じの余白を画面につけてくれる
repo = 'junegunn/goyo.vim'

# ------------------------------------
# Syntax Highlight
# ------------------------------------
[[plugins]]
repo = 'othree/html5.vim'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'evidens/vim-twig'

[[plugins]]
repo = 'posva/vim-vue'

[[plugins]]
repo = 'cespare/vim-toml'

# ------------------------------------
# HTML,CSS,JavaScript
# ------------------------------------
[[plugins]] # emmet
repo = 'mattn/emmet-vim'

[[plugins]] # 整形
repo = 'maksimr/vim-jsbeautify'

# [[plugins]] # npm install typescript-tools -g
# repo  = 'Quramy/tsuquyomi'
