# SCSS-Lint Configurations
# see also:
# https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md
linters:
  BangFormat:
    enabled: true
    space_before_bang: true
    space_after_bang: false
  ColorVariable:
    enabled: false
  Comment:
    enabled: false
  DebugStatement:
    enabled: false
  DeclarationOrder:
    enabled: true
  ElsePlacement:
    enabled: true
    style: 'same_line'
  ImportPath:
    enabled: true
    leading_underscore: true
    filename_extension: false
  MergeableSelector:
    enabled: true
    force_nesting: true
  NameFormat:
    enabled: false
  PlaceholderInExtend:
    enabled: false
  PropertySpelling:
    enabled: true
    # 特殊な新規プロパティ名が登場したら、随時追加
    extra_properties:
      - behavior
  SelectorDepth:
    enabled: false
  UnnecessaryParentReference:
    enabled: true
  UrlFormat:
    enabled: false
